# Generated by Django 4.0.3 on 2022-03-24 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_presentacion_unidadmedida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('gramaje', models.DecimalField(decimal_places=4, max_digits=9)),
                ('peso', models.DecimalField(decimal_places=4, max_digits=9)),
                ('stock_minimo', models.DecimalField(decimal_places=4, max_digits=9)),
                ('costo', models.DecimalField(decimal_places=4, max_digits=9)),
                ('estado', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.presentacion')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.subcategoria')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.unidadmedida')),
            ],
        ),
    ]
