# Generated by Django 4.0.3 on 2022-03-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0007_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='forma_aplicacion',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
    ]
