# Generated by Django 4.0.3 on 2022-03-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0009_alter_producto_forma_aplicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='forma_aplicacion',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
