# Generated by Django 4.0.3 on 2022-03-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='actividad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_apertura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='siglas',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
