# Generated by Django 4.0.3 on 2022-03-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0003_piscina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piscina',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
