# Generated by Django 4.0.3 on 2022-03-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0004_alter_piscina_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piscina',
            name='dimension',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
    ]
