# Generated by Django 4.0.3 on 2022-03-26 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0005_alter_piscina_dimension'),
        ('Inventario', '0007_alter_producto_imagen'),
        ('Dieta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='dietas',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='dietas',
            name='mes',
        ),
        migrations.AddField(
            model_name='dietas',
            name='piscina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inicio.piscina'),
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dieta.anio')),
            ],
        ),
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dieta.mes')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleDietas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=9)),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dieta.dietas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.producto')),
            ],
        ),
        migrations.AlterField(
            model_name='dietas',
            name='dia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dieta.dias'),
        ),
    ]
