# Generated by Django 4.0.3 on 2022-03-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dieta', '0002_anio_remove_dietas_anio_remove_dietas_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mes',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mes',
            name='mes',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
