# Generated by Django 4.0.3 on 2022-03-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dieta', '0003_mes_numero_alter_mes_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dias',
            name='dia',
            field=models.DateField(unique=True),
        ),
    ]
