# Generated by Django 4.0.3 on 2022-03-29 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dieta', '0005_alter_dietas_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietas',
            name='dia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dieta.dias'),
        ),
    ]
