# Generated by Django 4.0.3 on 2022-03-30 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0010_alter_producto_forma_aplicacion'),
        ('Dieta', '0007_alter_dietas_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledietas',
            name='cantidad',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('detalle_dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dieta.detalledietas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.producto')),
            ],
        ),
    ]
