# Generated by Django 4.0.3 on 2022-03-30 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dieta', '0008_alter_detalledietas_cantidad_kardex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardex',
            name='detalle_dieta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dieta.detalledietas'),
        ),
    ]
