# Generated by Django 4.0.3 on 2022-03-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dieta', '0009_alter_kardex_detalle_dieta'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardex',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
